---
apiVersion: v1
kind: Namespace
metadata:
    name: myns
    labels: 
        dept: engineering
---
apiVersion: v1
kind: Pod
metadata:
    name: fortune-pod
    namespace: myns
    labels:
        dept: engineering
        app: fortune
spec:
    containers:
    - name: fortune-container
      image: tqhdocker/fortune:v2
      imagePullPolicy: IfNotPresent
      env: 
      - name: APP_PORT
        value: "8080"
      ports:
      - name: fortune-port
        containerPort: 8080